stages:
  - build-clibs
  - test

variables:
  SYS_CACHE_GNULINUX: "gmp-mpfr-sys-cache-gnulinux"

gnulinux-build-clibs:
  image: rust:1
  stage: build-clibs
  script:
  - mkdir $SYS_CACHE_GNULINUX
  - export GMP_MPFR_SYS_CACHE=$SYS_CACHE_GNULINUX
  - cargo check --no-default-features --features gmp-mpfr-sys/mpc,gmp-mpfr-sys/ctest -p gmp-mpfr-sys
  artifacts:
    paths:
    - $SYS_CACHE_GNULINUX
    expire_in: 1 day

gnulinux-beta:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=$SYS_CACHE_GNULINUX
  - rustup install beta
  - cargo +beta --version
  - rustc +beta --version
  - cargo +beta test --features serde -p gmp-mpfr-sys -p rug
  - cargo +beta test --release --features serde -p gmp-mpfr-sys -p rug
  - rustup component add rustfmt --toolchain beta
  - cargo +beta fmt -- --check
  - rustup component add clippy --toolchain beta
  - cargo +beta clippy -- -D warnings

gnulinux-stable:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=$SYS_CACHE_GNULINUX
  - rustup install stable
  - cargo +stable --version
  - rustc +stable --version
  - cargo +stable test --features serde -p gmp-mpfr-sys -p rug
  - cargo +stable test --release --features serde -p gmp-mpfr-sys -p rug

gnulinux-nightly:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=$SYS_CACHE_GNULINUX
  - rustup install nightly
  - cargo +nightly --version
  - rustc +nightly --version
  - cargo +nightly test --features serde -p gmp-mpfr-sys -p rug
  - cargo +nightly test --release --features serde -p gmp-mpfr-sys -p rug

gnulinux-1.18.0:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=$SYS_CACHE_GNULINUX
  - rustup install 1.18.0
  - cargo +1.18.0 --version
  - rustc +1.18.0 --version
  - cargo +1.18.0 test --features serde -p gmp-mpfr-sys -p rug
  - cargo +1.18.0 test --release --features serde -p gmp-mpfr-sys -p rug
