stages:
  - build-clibs
  - test

gnulinux-build-clibs:
  image: rust:1
  stage: build-clibs
  script:
  - mkdir gmp-mpfr-sys-cache-gnulinux
  - export GMP_MPFR_SYS_CACHE=gmp-mpfr-sys-cache-gnulinux
  - cargo check --no-default-features --features gmp-mpfr-sys/mpc,gmp-mpfr-sys/ctest -p gmp-mpfr-sys
  artifacts:
    paths:
    - gmp-mpfr-sys-cache-gnulinux
    expire_in: 1 day

gnulinux-beta:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=gmp-mpfr-sys-cache-gnulinux
  - rustup install beta
  - cargo +beta --version
  - rustc +beta --version
  - ./test-gitlab-ci.sh beta
  - rustup component add rustfmt --toolchain beta
  - cargo +beta fmt -- --check
  - rustup component add clippy --toolchain beta
  - cargo +beta clippy -- -D warnings

gnulinux-stable:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=gmp-mpfr-sys-cache-gnulinux
  - rustup install stable
  - cargo +stable --version
  - rustc +stable --version
  - ./test-gitlab-ci.sh stable

gnulinux-nightly:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=gmp-mpfr-sys-cache-gnulinux
  - rustup install nightly
  - cargo +nightly --version
  - rustc +nightly --version
  - ./test-gitlab-ci.sh nightly

gnulinux-1.18.0:
  image: rust:1
  stage: test
  dependencies:
  - gnulinux-build-clibs
  script:
  - export GMP_MPFR_SYS_CACHE=gmp-mpfr-sys-cache-gnulinux
  - rustup install 1.18.0
  - cargo +1.18.0 --version
  - rustc +1.18.0 --version
  - ./test-gitlab-ci.sh 1.18.0

