# Copyright © 2016–2019 University of Malta

# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.

stages:
  - clibs
  - test

before_script:
  - getconf LONG_BIT
  - rustup --version
  - if [ -n "$TOOLCHAIN" ]; then rustup install $TOOLCHAIN; fi
  - if [[ "$TOOLCHAIN" == beta* ]]; then rustup component add --toolchain $TOOLCHAIN rustfmt clippy; fi
  - if [ -d cargo/registry/cache ]; then rm -rf $CARGO_HOME/registry/cache && mkdir -p $CARGO_HOME/registry && cp -R cargo/registry/cache $CARGO_HOME/registry/ && echo Copied registry/cache; fi
  - (if cd $CARGO_HOME/registry && [ -d cache ]; then find cache -name \*.crate; fi)
  - export GMP_MPFR_SYS_CACHE=$CI_PROJECT_DIR/gmp-mpfr-sys-cache

after_script:
  - (cd $CARGO_HOME/registry && find cache -name \*.crate)
  - rm -rf cargo
  - mkdir -p cargo/registry
  - cp -R $CARGO_HOME/registry/cache cargo/registry/ && echo Updated registry/cache

clibs-x86_64-gnulinux:
  image: amd64/rust:1
  stage: clibs
  cache:
    key: $CI_JOB_NAME
    paths:
    - cargo/
    - gmp-mpfr-sys-cache/
  script:
  - cargo test --no-default-features --features "gmp-mpfr-sys/mpc gmp-mpfr-sys/ctest" -p gmp-mpfr-sys
  artifacts:
    paths:
    - cargo/
    - gmp-mpfr-sys-cache/
    expire_in: 1 day

beta-x86_64-gnulinux:
  image: amd64/rust:1
  stage: test
  dependencies:
  - clibs-x86_64-gnulinux
  variables:
    TOOLCHAIN: beta-x86_64
  script:
  - ./test-gitlab-ci.sh

stable-x86_64-gnulinux:
  image: amd64/rust:1
  stage: test
  dependencies:
  - clibs-x86_64-gnulinux
  variables:
    TOOLCHAIN: stable-x86_64
  script:
  - ./test-gitlab-ci.sh

nightly-x86_64-gnulinux:
  image: amd64/rust:1
  stage: test
  dependencies:
  - clibs-x86_64-gnulinux
  variables:
    TOOLCHAIN: nightly-x86_64
  script:
  - ./test-gitlab-ci.sh

1.31.1-x86_64-gnulinux:
  image: amd64/rust:1
  stage: test
  dependencies:
  - clibs-x86_64-gnulinux
  variables:
    TOOLCHAIN: 1.31.1-x86_64
  script:
  - ./test-gitlab-ci.sh

stable-x86_64-gnulinux-valgrind:
  image: amd64/rust:1
  stage: test
  dependencies:
  - clibs-x86_64-gnulinux
  variables:
    TOOLCHAIN: stable-x86_64
  script:
  - apt-get install -y -qq valgrind
  - ./extract_doc_tests.sh
  - cargo +$TOOLCHAIN test --features serde --lib
  - valgrind --leak-check=full --error-exitcode=1 "$(ls target/debug/deps/rug* | grep -v '\.d')"
  - cargo +$TOOLCHAIN test --release --features serde --lib
  - valgrind --leak-check=full --error-exitcode=1 "$(ls target/release/deps/rug* | grep -v '\.d')"
  - ./extract_doc_tests.sh restore

clibs-i686-gnulinux:
  image: i386/rust:1
  stage: clibs
  cache:
    key: $CI_JOB_NAME
    paths:
    - cargo/
    - gmp-mpfr-sys-cache/
  script:
  - cargo test --no-default-features --features "gmp-mpfr-sys/mpc gmp-mpfr-sys/ctest" -p gmp-mpfr-sys
  artifacts:
    paths:
    - cargo/
    - gmp-mpfr-sys-cache/
    expire_in: 1 day

beta-i686-gnulinux:
  image: i386/rust:1
  stage: test
  dependencies:
  - clibs-i686-gnulinux
  variables:
    TOOLCHAIN: beta-i686
  script:
  - ./test-gitlab-ci.sh

stable-i686-gnulinux:
  image: i386/rust:1
  stage: test
  dependencies:
  - clibs-i686-gnulinux
  variables:
    TOOLCHAIN: stable-i686
  script:
  - ./test-gitlab-ci.sh

nightly-i686-gnulinux:
  image: i386/rust:1
  stage: test
  dependencies:
  - clibs-i686-gnulinux
  variables:
    TOOLCHAIN: nightly-i686
  script:
  - ./test-gitlab-ci.sh

1.31.1-i686-gnulinux:
  image: i386/rust:1
  stage: test
  dependencies:
  - clibs-i686-gnulinux
  variables:
    TOOLCHAIN: 1.31.1-i686
  script:
  - ./test-gitlab-ci.sh

stable-i686-gnulinux-valgrind:
  image: i386/rust:1
  stage: test
  dependencies:
  - clibs-i686-gnulinux
  variables:
    TOOLCHAIN: stable-i686
  script:
  - apt-get install -y -qq valgrind
  - ./extract_doc_tests.sh
  - cargo +$TOOLCHAIN test --features serde --lib
  - valgrind --leak-check=full --error-exitcode=1 "$(ls target/debug/deps/rug* | grep -v '\.d')"
  - cargo +$TOOLCHAIN test --release --features serde --lib
  - valgrind --leak-check=full --error-exitcode=1 --suppressions=i686-release.supp "$(ls target/release/deps/rug* | grep -v '\.d')"
  - ./extract_doc_tests.sh restore
